from django.db import migrations, models
import django.db.models.deletion
import datetime


class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth','0012_alter_user_first_name_max_length')]

    operations = [
        migrations.CreateModel('UserProfile', fields=[
            ('id', models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ('role', models.CharField(choices=[('admin','Administrator'),('staff','Lab Staff'),('doctor','Doctor'),('patient','Patient')],default='patient',max_length=20)),
            ('phone', models.CharField(blank=True,max_length=20)),
            ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to='auth.user')),
        ]),
        migrations.CreateModel('Doctor', fields=[
            ('id', models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ('doc_id', models.CharField(editable=False,max_length=20,unique=True)),
            ('name', models.CharField(max_length=150)),
            ('qualification', models.CharField(blank=True,max_length=100)),
            ('specialization', models.CharField(blank=True,max_length=100)),
            ('mobile', models.CharField(max_length=20)),
            ('email', models.EmailField(blank=True,max_length=254)),
            ('hospital', models.CharField(blank=True,max_length=200)),
            ('address', models.TextField(blank=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ]),
        migrations.CreateModel('Test', fields=[
            ('id', models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ('name', models.CharField(max_length=200)),
            ('category', models.CharField(choices=[('Haematology','Haematology'),('Biochemistry','Biochemistry'),('Serology','Serology'),('Clinical Pathology','Clinical Pathology'),('Histopathology','Histopathology'),('Hormones','Hormones')],default='Haematology',max_length=50)),
            ('price', models.DecimalField(decimal_places=2,default=0,max_digits=8)),
            ('sample', models.CharField(max_length=30,default='Blood (Plain)')),
            ('tat', models.CharField(blank=True,max_length=50)),
            ('active', models.BooleanField(default=True)),
        ], options={'ordering':['category','name']}),
        migrations.CreateModel('TestParameter', fields=[
            ('id', models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ('param_name', models.CharField(max_length=200)),
            ('unit', models.CharField(blank=True,max_length=50)),
            ('lower_limit', models.FloatField(blank=True,null=True)),
            ('upper_limit', models.FloatField(blank=True,null=True)),
            ('is_text', models.BooleanField(default=False)),
            ('sort_order', models.PositiveIntegerField(default=0)),
            ('test_method', models.CharField(blank=True,max_length=200)),
            ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='parameters',to='lab.test')),
        ], options={'ordering':['sort_order']}),
        migrations.CreateModel('Patient', fields=[
            ('id', models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ('patient_id', models.CharField(editable=False,max_length=20,unique=True)),
            ('first_name', models.CharField(max_length=100)),
            ('last_name', models.CharField(blank=True,max_length=100)),
            ('age', models.PositiveIntegerField()),
            ('gender', models.CharField(choices=[('Male','Male'),('Female','Female'),('Child (M)','Child (M)'),('Child (F)','Child (F)'),('Other','Other')],default='Male',max_length=20)),
            ('mobile', models.CharField(max_length=20)),
            ('email', models.EmailField(blank=True,max_length=254)),
            ('address', models.TextField(blank=True)),
            ('blood_group', models.CharField(blank=True,max_length=5)),
            ('priority', models.CharField(choices=[('Normal','Normal'),('Urgent','Urgent'),('Emergency','Emergency')],default='Normal',max_length=20)),
            ('photo', models.ImageField(blank=True,null=True,upload_to='photos/')),
            ('registered_at', models.DateTimeField(auto_now_add=True)),
            ('referring_doctor', models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='lab.doctor')),
            ('user', models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='patient_profile',to='auth.user')),
        ], options={'ordering':['-registered_at']}),
        migrations.CreateModel('Booking', fields=[
            ('id', models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ('receipt_id', models.CharField(editable=False,max_length=30,unique=True)),
            ('booking_date', models.DateField(default=datetime.date.today)),
            ('sample_date', models.DateField(default=datetime.date.today)),
            ('status', models.CharField(choices=[('pending','Pending'),('sample_collected','Sample Collected'),('processing','Processing'),('ready','Ready'),('delivered','Delivered')],default='sample_collected',max_length=20)),
            ('subtotal', models.DecimalField(decimal_places=2,default=0,max_digits=10)),
            ('discount_pct', models.DecimalField(decimal_places=2,default=0,max_digits=5)),
            ('referral_pct', models.DecimalField(decimal_places=2,default=0,max_digits=5)),
            ('discount_amt', models.DecimalField(decimal_places=2,default=0,max_digits=10)),
            ('total', models.DecimalField(decimal_places=2,default=0,max_digits=10)),
            ('paid', models.DecimalField(decimal_places=2,default=0,max_digits=10)),
            ('due', models.DecimalField(decimal_places=2,default=0,max_digits=10)),
            ('payment_mode', models.CharField(choices=[('Cash','Cash'),('UPI/GPay','UPI/GPay'),('Card','Card'),('Cheque','Cheque'),('Credit','Credit')],default='Cash',max_length=20)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='bookings',to='lab.patient')),
            ('ref_doctor', models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='lab.doctor')),
            ('tests', models.ManyToManyField(blank=True,to='lab.test')),
            ('created_by', models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='bookings_created',to='auth.user')),
        ], options={'ordering':['-created_at']}),
        migrations.CreateModel('Report', fields=[
            ('id', models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ('report_id', models.CharField(editable=False,max_length=30,unique=True)),
            ('report_date', models.DateField(default=datetime.date.today)),
            ('remarks', models.TextField(blank=True)),
            ('is_finalized', models.BooleanField(default=False)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='reports',to='lab.booking')),
            ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='lab.test')),
        ], options={'ordering':['-created_at']}),
        migrations.CreateModel('ReportResult', fields=[
            ('id', models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),
            ('param_name', models.CharField(max_length=200)),
            ('value', models.CharField(blank=True,max_length=200)),
            ('unit', models.CharField(blank=True,max_length=50)),
            ('lower_limit', models.FloatField(blank=True,null=True)),
            ('upper_limit', models.FloatField(blank=True,null=True)),
            ('flag', models.CharField(choices=[('normal','Normal'),('high','High ↑'),('low','Low ↓'),('text','Text'),('critical','Critical')],default='normal',max_length=10)),
            ('sort_order', models.PositiveIntegerField(default=0)),
            ('parameter', models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,to='lab.testparameter')),
            ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='results',to='lab.report')),
        ], options={'ordering':['sort_order']}),
    ]
