# Generated by Django 4.2.29 on 2026-04-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_test_fullname_param_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='letterhead_image',
            field=models.ImageField(blank=True, help_text='Full letterhead image (replaces entire header in PDF if set)', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload lab logo (shown in PDF header)', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_bill_margin_bottom',
            field=models.PositiveIntegerField(default=0, help_text='Bill PDF - Bottom margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_bill_margin_left',
            field=models.PositiveIntegerField(default=0, help_text='Bill PDF - Left margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_bill_margin_right',
            field=models.PositiveIntegerField(default=0, help_text='Bill PDF - Right margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_bill_margin_top',
            field=models.PositiveIntegerField(default=0, help_text='Bill PDF - Top margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_bulk_margin_bottom',
            field=models.PositiveIntegerField(default=0, help_text='Bulk PDF - Bottom margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_bulk_margin_left',
            field=models.PositiveIntegerField(default=0, help_text='Bulk PDF - Left margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_bulk_margin_right',
            field=models.PositiveIntegerField(default=0, help_text='Bulk PDF - Right margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_bulk_margin_top',
            field=models.PositiveIntegerField(default=0, help_text='Bulk PDF - Top margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_footer_image',
            field=models.ImageField(blank=True, help_text='Optional footer image/stamp', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_single_margin_bottom',
            field=models.PositiveIntegerField(default=0, help_text='Single PDF - Bottom margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_single_margin_left',
            field=models.PositiveIntegerField(default=0, help_text='Single PDF - Left margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_single_margin_right',
            field=models.PositiveIntegerField(default=0, help_text='Single PDF - Right margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='pdf_single_margin_top',
            field=models.PositiveIntegerField(default=0, help_text='Single PDF - Top margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_bill_margin_bottom',
            field=models.PositiveIntegerField(default=96, help_text='Bill Print - Bottom margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_bill_margin_left',
            field=models.PositiveIntegerField(default=0, help_text='Bill Print - Left margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_bill_margin_right',
            field=models.PositiveIntegerField(default=0, help_text='Bill Print - Right margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_bill_margin_top',
            field=models.PositiveIntegerField(default=100, help_text='Bill Print - Top margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_bulk_margin_bottom',
            field=models.PositiveIntegerField(default=96, help_text='Bulk Print - Bottom margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_bulk_margin_left',
            field=models.PositiveIntegerField(default=0, help_text='Bulk Print - Left margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_bulk_margin_right',
            field=models.PositiveIntegerField(default=0, help_text='Bulk Print - Right margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_bulk_margin_top',
            field=models.PositiveIntegerField(default=100, help_text='Bulk Print - Top margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_single_margin_bottom',
            field=models.PositiveIntegerField(default=96, help_text='Single Print - Bottom margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_single_margin_left',
            field=models.PositiveIntegerField(default=0, help_text='Single Print - Left margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_single_margin_right',
            field=models.PositiveIntegerField(default=0, help_text='Single Print - Right margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='print_single_margin_top',
            field=models.PositiveIntegerField(default=100, help_text='Single Print - Top margin (px)'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='show_timing_bar',
            field=models.BooleanField(default=True, help_text='Show timing bar in PDF'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='signature_ansari',
            field=models.ImageField(blank=True, help_text='Dr. M. Ahmad Ansari signature image', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='signature_kumar',
            field=models.ImageField(blank=True, help_text='N. Kumar signature image', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='signature_maurya',
            field=models.ImageField(blank=True, help_text='Dr. V.P. Maurya signature image', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='labsettings',
            name='signature_saleem',
            field=models.ImageField(blank=True, help_text='Dr. M. Saleem signature image', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='custom_display_id',
            field=models.CharField(blank=True, help_text='Custom ID on reports', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='custom_report_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reportresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='test',
            name='full_name',
            field=models.CharField(blank=True, help_text='Optional full name (e.g. "Complete Blood Count" for CBC). If set, this shows on reports instead of short name.', max_length=300),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='test',
            name='sample',
            field=models.CharField(choices=[('Blood (EDTA)', 'Blood (EDTA)'), ('Blood (Plain)', 'Blood (Plain)'), ('Urine', 'Urine'), ('Stool', 'Stool'), ('Swab', 'Swab'), ('Sputum', 'Sputum'), ('Semen', 'Semen'), ('Tissue', 'Tissue'), ('Sodium Citrate', 'Sodium Citrate'), ('Heparin', 'Heparin'), ('Floride', 'Floride')], default='Blood (Plain)', max_length=30),
        ),
        migrations.AlterField(
            model_name='testnote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testnote',
            name='note_text',
            field=models.TextField(help_text='Note printed at bottom of this test report (e.g. cell morphology note for CBC)'),
        ),
        migrations.AlterField(
            model_name='testparameter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
